### ISSUE TITLE
Proposal: Change the free net limit to 1500

### ISSUE THREAD

**Issue by vita-coffee** [tronprotocol/tips#320] opened 2021-08-16 10:02 UTC
# Proposal: Change the free net limit to 1500

## Introduction

The free net limit is the free bandwidth resource that can be used by the users to decrease the transaction fees. At present, the free net limit is set as a default value of 5000. But recently, some malicious users generated lots of fraudulent TRC10 transactions (please refer to issue #286 for more details) by abusing the free bandwidth resources.  These fraudulent TRC10 transactions can be restrained by increasing their cost, and decreasing the free net limit is an option.

## Motivation

To restrain the fraudulent transactions, the community proposes to decrease the free net limit from 5000 to 1500, which can limit users to send about 5 free transactions (the average bandwidth consumption of a transaction is about 280) for daily use.

## Timeline

The estimated timeline
- Creation time of the voting request: 31st August. 2021
- The estimated effective time of voting request: 3rd September. 2021 

## How to initiate the voting request
Change the free net limit  to 1500:
- createProposal 61 1500

## Background

The TRON network brings many benefits to users due to its low transaction fees and fast transaction speed. But this also brings many side effects. For example, malicious users can abuse the low-fee transactions to send many useless transactions and result in a bad influence on the TRON network. Even if proposal #286 has increased the bandwidth unit price and system contract creating account fee, it is still not enough to limit the low-value TRC-10 transactions. Malicious users can still abuse the free bandwidth resources to send fraudulent transactions.  For example,  for the scam token (https://tronscan.org/#/token/1004324/),  it has controlled 37, 871 addresses to airdrop fraudulent tokens to users continually. Each address can send about 17 free transactions in a day (Currently,  the free net limit of an account is  5000, for the average 280 bandwidth consumption of a transaction,  it allows the account to send about 17 (5000/280) free transactions in a day),  then the scam token can send about 643, 807 fraudulent transactions every day without any cost,  which will lead to a great waste of resources in TRON network.

As shown in the following figure,  TRC10 transactions consist 50% of transactions in the TRON network.  

![image](https://user-images.githubusercontent.com/70734475/129543720-23d74772-54f4-4f73-93cd-8c46be8b6ccb.png)

Some TRC10 tokens even trick the defenseless users to steal their assets, as shown in #286.  fraudulent projects may attach advertisements to the transactions by using the free bandwidth resources, which will influence the healthy environment of the TRON network, for example:  (https://tronscan.org/#/transaction/b78f594bf9a8c9251c7a9ab311c2e2aeedb24e32289cf32f73841a11ed42e595) :

![image](https://user-images.githubusercontent.com/70734475/129543341-ca2534dd-196f-453e-b313-bfa0178eced2.png)

## Recommended solution

For most users, 3~5 transactions are enough for daily use. To balance off the normal transactions and fraudulent transactions,  we need to change the free net limit, namely:
Change the free net limit from 5000 to 1500

## The Impact Analysis

After changing the free net limit to 1500,  it allows an account to send 5 (1500/280 )  free transactions in a day. On one hand, it can satisfy the requirement of daily use for normal users, on the other hand,  it can limit the malicious users from sending worthless transactions freely.  This proposal will play an important role in saving bandwidth resources and improving the TRON network.

**Comment by Vita-Clotilde** [comment] 2021-08-16 10:31
I agree with this proposal. Recently, every transaction sent out will receive a lot of junk coins. Although I will not click any links in it, these messages are very annoying. 
I believe these spammers mainly rely on free bandwidth to do these things, so this change should solve the problems to some extent.
And even for DAPP developers, relative to energy, bandwidth consumption can be said to be minimal, and this should not have much impact on them.

**Comment by woaichixigua07** [comment] 2021-08-16 10:49
Sending about 5 free transactions per day would be enough for most of the average users, and it would also prevent some spam transactions. My address receives a lot of spam TRC10 token transfers every day, so if this proposal passes it will have a positive effect.

**Comment by hitlxy** [comment] 2021-08-16 12:27
Yes, the previous proposal cannot fully prevent the fraudulent TRC10 transactions, because they have a lot of free bandwidth resources, and sending an fraudulent transaction costs noting. 
I am shocked of the number of trc10 transactions，half of the total transactions in the Tron network. And for me I don’t create trc10 trasaction, and I think trc10 token should be used very rarely. But the reality is just the opposite.
So I wish both the two proposal together can prevent the fraudulent trc10 txns.
And it is nice that five free transactions are sufficient.

**Comment by a49688448** [comment] 2021-08-17 02:15
I support increasing transaction fees, which can increase the cost of spam transactions. The more TRX burned, it will also benefit TRX, which is beneficial to TRX believers like us.

But at the same time, I am also worried that individual small developers feel that transaction costs are high and move to cheaper chains for development, which is not conducive to the long-term development of the TRON ecosystem.

What I want to ask is, has the number of TRX transactions, the number of developers, and the number of DAPPs dropped since the increase in transaction fees until now?

**Comment by joker-gdb** [comment] 2021-08-17 02:54
Bandwidth accounts for a small percentage of the overall transaction costs, so this has little impact on user developers. I even think that the daily free bandwidth is enough to pay for one transfer transaction.

**Comment by call-me-nobody** [comment] 2021-08-17 02:57
First of all, I agree that this is a very good proposal. Compared to #286, this is the correct method that can effectively inhibit TRC10 transactions. Judging from the current transaction data on the main network, the number of TRC10 transactions is indeed a bit outrageous. Certain measures should be taken to improve these situations.

but, still, I got several questions.
1. First of all, how the 5 free transactions are calculated and estimated. If there are exact data, I hope that the community can show the relevant data and calculation methods, so that developers can more clearly understand why it is 5.
2. Continuing with the example above, the project has 38K addresses, five times a day, they still have close to 200K free transactions, and this number is still very large, do you have any backup solution if this method not working? 
3. At the same time, we also hope to see that the community can analyze the TRC10 transaction data in the past 3 months and list the proportion of each token so that we can more clearly understand how many projects are abusing free bandwidth, then a correct decision can be made based on these goals and targeted these projects, thanks.

**Comment by Cletitia** [comment] 2021-08-17 03:47
The most spams I’ve received are TRC-10 transfers or small-value TRX transfers. Free bandwidth gives scammars chances to send low-cost transactions. 
Honestly, I can’t see any TRC-10 tokens other from BTT is valuable, or they are simply trash tokens, but TRC-10 related transactions have taken over half of the net resources(from the above statictics), this is unhealthy.
However, as for smart contracts, energy cost is the bulk. So I can say this proposal is a precise blow to the scammars.

**Comment by Federico2014** [comment] 2021-08-17 03:49
> First of all, I agree that this is a very good proposal. Compared to #286, this is the correct method that can effectively inhibit TRC10 transactions. Judging from the current transaction data on the main network, the number of TRC10 transactions is indeed a bit outrageous. Certain measures should be taken to improve these situations.
> 
> but, still, I got several questions.
> 
> 1. First of all, how the 5 free transactions are calculated and estimated. If there are exact data, I hope that the community can show the relevant data and calculation methods, so that developers can more clearly understand why it is 5.
> 2. Continuing with the example above, the project has 38K addresses, five times a day, they still have close to 200K free transactions, and this number is still very large, do you have any backup solution if this method not working?
> 3. At the same time, we also hope to see that the community can analyze the TRC10 transaction data in the past 3 months and list the proportion of each token so that we can more clearly understand how many projects are abusing free bandwidth, then a correct decision can be made based on these goals and targeted these projects, thanks.

I totally agree with what you said. Limiting the TRC10 transactions is necessary.  From the daily transactions statistics (https://tronscan.org/#/data/stats/txOverviewStatsType), the maximum daily transactions amount is about  9.3 million, the daily active account amount (https://tronscan.org/#/data/stats/activeAccounts) is about 2.4 million,  the average daily number of transactions for an account is about  3.8.  Considering some redundancy, I think 5 free transactions may be plausible.

**Comment by Federico2014** [comment] 2021-08-17 04:19
> I think that increasing transaction fees, which can increase the cost of spam transactions. The more TRX burned, it will also benefit TRX, which is beneficial to TRX believers like us.
> 
> But at the same time, I am also worried that individual small developers feel that transaction costs are high and move to cheaper chains for development, which is not conducive to the long-term development of the TRON ecosystem.
> 
> What I want to ask is, has the number of TRX transactions, the number of developers, and the number of DAPPs dropped since the increase in transaction fees until now?

From the statistics：https://tronscan.org/#/data/stats/txOverviewStatsType,  the daily transactions have already dropped in Auguest.

**Comment by vae520283995** [comment] 2021-08-17 06:42
Very good proposal, I am harassed by fraudulent trc10 every day, and I hope to launch it on the mainnet soon

**Comment by Guerreru** [comment] 2021-08-17 20:14
Hello,

I think should put more active SRs instead so raise the number from 27 to 32, maybe more and it will be resolved which increases the throughput/bandwidth instead of overworking the current SRs and trying to push price hikes that will not resolve anything. 

Also make sure the SRs really have at least the minimum current hardware requirements vs using a 16-cores server from 2006. Help prevent contracts from timing out and burning huge amounts of ENERGY/TRX, due to queue on super busy SR node.

Maybe one workaround on the software would be to delay transactions from such reported and confirmed fraud tokens. 
Node to keep a pool of token ids / contracts of them or if already have one for all, add a fraud tag column, so the node delays these and use only up to 10% of processing power.

Increase the capacity, not just the fee.

**Comment by ustx** [comment] 2021-08-17 20:44
Wouldn't it be easier to just stop issuing new TRC10 tokens and limit usage to legit ones? Everyone knows that 99.9% of TRC are just scam tokens with no value. The blockchain value is in the TRC20 ecosystem (tokens and dApps). BW is useful for most legit users. Reducing free BW will not stop TRC10 scam transfers, will just make is slightly more expensive. Tron needs to stop TRC10 from being used (apart from BTT and a few others). Just my 2c.

**Comment by Guerreru** [comment] 2021-08-17 21:11
Apart from my comment above, I just realized something: the webpage on https://tronscan.org/#/data/stats/txOverviewStatsType (which is the Daily Transactions image attached to the original post above) shows that on all time Transactions have not peaked above 9.3M ever. The Tron network is supposed to handle 2,000 transactions per second, down from 10,000 transactions per second with no transaction fees after the 2018 WhitePaper version. So 2000 Transactions x 86400 seconds in a day are 172.8M transactions per day. So are you telling me that now it has problems even handling the 9.3M it peaked last month ?

**Comment by Federico2014** [comment] 2021-08-18 03:40
> Apart from my comment above, I just realized something: the webpage on https://tronscan.org/#/data/stats/txOverviewStatsType (which is the Daily Transactions image attached to the original post above) shows that on all time Transactions have not peaked above 9.3M ever. The Tron network is supposed to handle 2,000 transactions per second, down from 10,000 transactions per second with no transaction fees after the 2018 WhitePaper version. So 2000 Transactions x 86400 seconds in a day are 172.8M transactions per day. So are you telling me that now it has problems even handling the 9.3M it peaked last month ?

Hey, this doesn't mean it has problems handing the 9.3M transactions, it has a long distance to reach the upper limit.  The proposal just aims to limit fraudulent transactions and prevent bandwidth resources waste.

**Comment by Federico2014** [comment] 2021-08-18 03:48
> Hello,
> 
> I think should put more active SRs instead so raise the number from 27 to 32, maybe more and it will be resolved which increases the throughput/bandwidth instead of overworking the current SRs and trying to push price hikes that will not resolve anything.
> 
> Also make sure the SRs really have at least the minimum current hardware requirements vs using a 16-cores server from 2006. Help prevent contracts from timing out and burning huge amounts of ENERGY/TRX, due to queue on super busy SR node.
> 
> Maybe one workaround on the software would be to delay transactions from such reported and confirmed fraud tokens.
> Node to keep a pool of token ids / contracts of them or if already have one for all, add a fraud tag column, so the node delays these and use only up to 10% of processing power.
> 
> Increase the capacity, not just the fee.

Very good idea.  Currently,  the TRON network doesn't lack the bandwidth resource,  but to prevent its abuse and waste.  As for adding the blacklist for the spam tokens, it seems to violate the spirit of censorship-resistance of the public chain, which may be infeasible.

**Comment by arcom7707** [comment] 2021-08-19 15:30
> # Proposal: Change the free net limit to 1500
> ## Introduction
> The free net limit is the free bandwidth resource that can be used by the users to decrease the transaction fees. At present, the free net limit is set as a default value of 5000. But recently, some malicious users generated lots of fraudulent TRC10 transactions (please refer to issue #286 for more details) by abusing the free bandwidth resources. These fraudulent TRC10 transactions can be restrained by increasing their cost, and decreasing the free net limit is an option.
> 
> ## Motivation
> To restrain the fraudulent transactions, the community proposes to decrease the free net limit from 5000 to 1500, which can limit users to send about 5 free transactions (the average bandwidth consumption of a transaction is about 280) for daily use.
> 
> ## Timeline
> The estimated timeline
> 
> * Creation time of the voting request: 31st August. 2021
> * The estimated effective time of voting request: 3rd September. 2021
> 
> ## How to initiate the voting request
> Change the free net limit to 1500:
> 
> * createProposal 61 1500
> 
> ## Background
> The TRON network brings many benefits to users due to its low transaction fees and fast transaction speed. But this also brings many side effects. For example, malicious users can abuse the low-fee transactions to send many useless transactions and result in a bad influence on the TRON network. Even if proposal #286 has increased the bandwidth unit price and system contract creating account fee, it is still not enough to limit the low-value TRC-10 transactions. Malicious users can still abuse the free bandwidth resources to send fraudulent transactions. For example, for the scam token (https://tronscan.org/#/token/1004324/), it has controlled 37, 871 addresses to airdrop fraudulent tokens to users continually. Each address can send about 17 free transactions in a day (Currently, the free net limit of an account is 5000, for the average 280 bandwidth consumption of a transaction, it allows the account to send about 17 (5000/280) free transactions in a day), then the scam token can send about 643, 807 fraudulent transactions every day without any cost, which will lead to a great waste of resources in TRON network.
> 
> As shown in the following figure, TRC10 transactions consist 50% of transactions in the TRON network.
> 
> ![image](https://user-images.githubusercontent.com/70734475/129543720-23d74772-54f4-4f73-93cd-8c46be8b6ccb.png)
> 
> Some TRC10 tokens even trick the defenseless users to steal their assets, as shown in #286. fraudulent projects may attach advertisements to the transactions by using the free bandwidth resources, which will influence the healthy environment of the TRON network, for example: (https://tronscan.org/#/transaction/b78f594bf9a8c9251c7a9ab311c2e2aeedb24e32289cf32f73841a11ed42e595) :
> 
> ![image](https://user-images.githubusercontent.com/70734475/129543341-ca2534dd-196f-453e-b313-bfa0178eced2.png)
> 
> ## Recommended solution
> For most users, 3~5 transactions are enough for daily use. To balance off the normal transactions and fraudulent transactions, we need to change the free net limit, namely:
> Change the free net limit from 5000 to 1500
> 
> ## The Impact Analysis
> After changing the free net limit to 1500, it allows an account to send 5 (1500/280 ) free transactions in a day. On one hand, it can satisfy the requirement of daily use for normal users, on the other hand, it can limit the malicious users from sending worthless transactions freely. This proposal will play an important role in saving bandwidth resources and improving the TRON network.

**Comment by vita-coffee** [comment] 2021-08-30 09:13
This discussion has been going on for some time, and I am very happy that most devs agree with this proposal. Now it’s very close to the time to initiate a voting request, so I hope https://github.com/cryptoguyinza can help us to initiate this request, @cryptoguyinza would you be able to help us? thanks.

**Comment by cryptoguyinza** [comment] 2021-08-30 10:30
> This discussion has been going on for some time, and I am very happy that most devs agree with this proposal. Now it’s very close to the time to initiate a voting request, so I hope https://github.com/cryptoguyinza can help us to initiate this request, @cryptoguyinza would you be able to help us? thanks.

Busy reviewing. If all is fine will create for tomorrow. Thanks

**Comment by Benson0224** [comment] 2021-09-03 10:02
Thank everyone for contributing to this proposal. now it is got approved on the main net. check detail at : https://tronscan.org/#/proposal/69

This issue will be closed as no more action needed, thanks again.

**Closed by Benson0224** 2021-09-03 10:02 UTC

**Comment by charmful0x** [comment] 2021-09-03 20:20
instead of keep pushing restrictions on TRC10 TXs (including TRX ones as TRX is a TRC10 token), it's much easier to create a universal blacklist dataset API that can be fetched to retrieve blacklisted TRC10 IDs, thus blacklist it on TRON owned apps' frontends (TronLink, TRONSCAN). This doesn't go against "blockchain & decentralization ethics" comparing with a staged voting.

Proposing votes is a good choice when not more than 50% of the SRs are owned/ by the TRON foundation. Justin has the quorum always (11 out of the 20 voters - or even more- are owned by the foundation), this is not calling voting! I know that @Benson0224 closed this TIP and it has been implemented in the mainnet, but expressing some respect to the devs community and stopping this TIP/voting staging will be better. Even the TIP issue has been opened by an unknown/fresh "developer" with ZERO public contributions, just forks. So I would call him/her a middle man?

**Comment by Guerreru** [comment] 2021-09-04 05:23
Oh so the free bandwidth was lowered to 1500, this has more to do because the SRs want to make money, they voted to lower the free bandwidth so that there are more fees. The SRs are acting like a board of directors of a corporation (fully centralized) where they look to stuff their pockets and look for ways to get more money from the consumers. Tron seems to begetting out of their original promise/whitepaper and can't handle such promised bandwidth.

**Comment by Benson0224** [comment] 2021-09-06 03:06
> Oh so the free bandwidth was lowered to 1500, this has more to do because the SRs want to make money, they voted to lower the free bandwidth so that there are more fees. The SRs are acting like a board of directors of a corporation (fully centralized) where they look to stuff their pockets and look for ways to get more money from the consumers. Tron seems to begetting out of their original promise/whitepaper and can't handle such promised bandwidth.

several things in your comments are wrong.
1. All the fees generated by TRX burning are transferred to the Blackhole account, no one can get fees. so this is not for SR to make more money. 
2. All SR are voted by the whole TRON community. and the TOP 27 SR decided whether the proposal will be approved or not,  The community believes that the TOP27 SR will make the best decision for the TRON ecosystem. from another point of view, not every proposal gets approved by TOP27 SR.
3. 1500 Bandwidth can afford around 5 ~ 6 free transactions, It should be OK for daily usage for normal users. and it will Effectively restrain the abuse of bandwidth.

**Comment by luozygithub** [comment] 2021-09-23 02:31
tronWeb.createAccount()方法为什么创建的账户没有助记词信息？

**Comment by deauna** [comment] 2021-10-01 04:44
up

**Comment by amhoba** [comment] 2022-01-19 15:19
Can we vote for the reversal of this proposal?
I have built an app that uses TRC10 (TRX) for its transactions. I need to send TRX to other people really frequently (for example 100 times a day), paying that much FEE will kill my application...

Please help me. please reverse this. Having free transactions means everything to me.

I want to vote for reversal, or better, create a reversal proposal, How can I do that?
@all

**Comment by amhoba** [comment] 2022-01-19 15:49
> Yes, the previous proposal cannot fully prevent the fraudulent TRC10 transactions, because they have a lot of free bandwidth resources, and sending an fraudulent transaction costs noting. I am shocked of the number of trc10 transactions，half of the total transactions in the Tron network. And for me I don’t create trc10 trasaction, and I think trc10 token should be used very rarely. But the reality is just the opposite. So I wish both the two proposal together can prevent the fraudulent trc10 txns. And it is nice that five free transactions are sufficient.

This is arrogance that you dont see others that use TRC10 (TRX) for their transactions.
TRX is a major benefit of the TRON Blockchain, How on earth can you say that it should be used rarely......?

App developers simply can not use a token (TRC20) for transactions within their applications, Cause it has really really high fees (6 ~ 7 TRX) and does not have a bandwidth mechanism at all.

Please take us all into account before applying / voting for a proposal ...

**Comment by amhoba** [comment] 2022-01-19 16:08
Can't we Just DISABLE the creation of more TRC10 tokens?
And just keep `TRX`?
And revert all those proposals that have been created so far to just address this simple problem (#286 #320)?

**Comment by Benson0224** [comment] 2022-01-20 03:13
> Can we vote for the reversal of this proposal? I have built an app that uses TRC10 (TRX) for its transactions. I need to send TRX to other people really frequently (for example 100 times a day), paying that much FEE will kill my application...
> 
> Please help me. please reverse this. Having free transactions means everything to me.
> 
> I want to vote for reversal, or better, create a reversal proposal, How can I do that?

I would suggest you Stake TRX to obtain free bandwidth.  
Please go to your account page on tronscan, https://tronscan.org/#/wallet  then you can see below entry of Staking. thanks. 
![image](https://user-images.githubusercontent.com/61768920/150265603-8fca7476-237c-4467-a7df-ba804008ec5a.png)

**Comment by amhoba** [comment] 2022-01-20 04:20
> > Can we vote for the reversal of this proposal? I have built an app that uses TRC10 (TRX) for its transactions. I need to send TRX to other people really frequently (for example 100 times a day), paying that much FEE will kill my application...
> > Please help me. please reverse this. Having free transactions means everything to me.
> > I want to vote for reversal, or better, create a reversal proposal, How can I do that?
> 
> I would suggest you Stake TRX to obtain free bandwidth. Please go to your account page on tronscan, https://tronscan.org/#/wallet then you can see below entry of Staking. thanks. ![image](https://user-images.githubusercontent.com/61768920/150265603-8fca7476-237c-4467-a7df-ba804008ec5a.png)

Staking is not an option for me. I knew that option exists long before. My application needs high send and receive transactions, I want to do microtransactions with tron, so I don't know how much TRX I need to be available at any point of time, so I can not dedicate X amount of TRX to be staked.

And even If I wanted to stake TRX for just bandwidth, It does not look economically feasible!
![image](https://user-images.githubusercontent.com/61024411/150272509-fc63198c-d6a1-47be-8359-ecf15791e103.png)
Just 93.825 bandwidth for 100 (7$) TRX ?????? Really???

Would you take this into consideration: https://github.com/tronprotocol/tips/issues/320#issuecomment-1016621545  ?

**Comment by vivian-kang** [comment] 2022-01-25 07:17
Hi @amhoba , 
[Staking for resource](https://developers.tron.network/docs/resource-model#bandwidth-points) can obtain not only the bandwidth but also TRON power (vote for revenue). 
And for the bandwidth obtained by staking, every 24 hours, the amount of the usage of Bandwidth points of an account will be reset to 0, so the next day, the account also have the corresponding amount of bandwidth. 
On the other hand, account can withdraw the TRX by unstaking operation. 
So suggest to get resource by staking TRX. Thanks.
