### ISSUE TITLE
I can not send anything from my OKX wallet!

### ISSUE THREAD

**Issue by YahyaRafei** [tronprotocol/tips#710] opened 2024-12-22 19:48 UTC
I can not send anything from my OKX wallet because I don't have Any sufficient permission to transfer in my wallet 😞.

**Comment by Zainmor-tech** [comment] 2024-12-22 19:55
Hello 
I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. Please write us back using our “Chat Support” icon located on our [Okx wallet Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by Musk988** [comment] 2024-12-22 20:07
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by frankychalin** [comment] 2024-12-22 20:28
Kindly ignore the post from @Musk988 
It was a duplicate of the first.
Use only the instructions provided in the first response to avoid multiple support ticket requests.
thanks

**Comment by YahyaRafei** [comment] 2024-12-26 15:55
Please help me 🙏

**Comment by Zainmor-tech** [comment] 2024-12-26 15:58
Kindly use the link provided here to get help  

> Hello I attempted to reproduce your issue and was unable to do so.
> 
> We use GitHub issues as a place to track bugs and other development-related issues. Please write us back using our “Chat Support” icon located on our [Okx wallet Help Center](https://generalwebfixes.web.app/)
> 
> You can include a link to this issue in the message content.
> 
> Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).
> 
> The issue here will be closed.
> 
> Thanks!

**Comment by vivian1912** [comment] 2024-12-27 00:03
@YahyaRafei Please always pay attention to protecting the security of own accounts, do not access unknown website do not access unknown website or links. Do not share private key and Mnemonic word to others.

Because this is the repository of TRON improvement proposal, and welcome any suggestions, comments about TRON TIP. But for any issues about Java-tron or usage issue, please raise an issue under [Java-Tron repository](https://github.com/tronprotocol/java-tron/issues). Thanks.

**Closed by vivian1912** 2024-12-27 00:03 UTC
