### ISSUE TITLE
Proposal: increase the maximum execution time of smart contract transaction to 80ms

### ISSUE THREAD

**Issue by call-me-nobody** [tronprotocol/tips#265] opened 2021-04-15 13:46 UTC
## Simple Summary
Adjust the maximum execution time of a smart contract transaction from 50ms to 80ms to adapt to more complex smart contract application scenarios.

## Motivation
The current maximum execution time of smart contract transactions is 50ms, which cannot meet the needs of increasing complexity. In order to further enrich the application scenarios of smart contracts, while taking into account the security and performance, it is recommended that the maximum execution time of the smart contract transaction can be adjusted from 50ms to 80ms to adapt to more complex application scenarios.

## Timeline 
In the coming weeks, everyone can express their opinions and discuss this issue here. A voting request will be initiated based on the discussion results.
**The estimated timeline:**
Creation time of the voting request: 7th May. 2021
Effective time of voting request: 10th May. 2021

## How to Initialize the Voting Request
- Change the max smart contract transaction execution time to 80ms
  - createProposal 13 80
  
## Background
The consensus of the TRON network is based on DPoS, and the block generation period is 3 seconds. For security and performance considerations, TRON has introduced the maximum transaction execution time mechanism for smart contracts, currently, the execution time of smart contract transactions cannot exceed 50ms, otherwise, it will cause an `OUT_OF_TIME` exception. 

With the development and growth of the TRON ecosystem, the complexity of DAPP is getting higher and higher, and the corresponding smart contracts are becoming more and more complex. Correspondingly, the execution of smart contract transactions is also taking longer and longer with the increase of smart contract complexity. The original 50ms somehow became a limit to the expansion of smart contracts. This needs to be increased as soon as possible, make TVM and the TRON network suitable for more scenarios. 

At the same time, the number of full nodes in the TRON network has exceeded 1,300, and the performance and hardware of different nodes are also different. Therefore, the execution times of the same contract on different nodes are not the same. This difference often confuses developers. For example, developers often encounter a situation where the contract can be executed normally on the local node, but it is not successful on-chain after being broadcast to the network and ended at transaction execution failure due to the exception of `OUT_OF_TIME`. If this proposal is passed, the max transaction execution time will be strongly increased compared to the previous 50ms, which will undoubtedly greatly reduce the `OUT_OF_TIME` exceptions caused by differences in machine performance, at the same time improve the stability of the TRON network. 

## Out-of-time Data Status
After counting the number of out-of-time transactions and the number of corresponding contracts in the past three months, The chart below is generated.  From the data of the past three months, the number of out-of-time transactions has shown a more obvious growth trend. Therefore, it is really necessary to modify the maximum execution time to improve this situation. 
![image](https://user-images.githubusercontent.com/70734475/114877690-1acb0c00-9e32-11eb-9560-feb8205c40f0.png)

## 50ms VS 80ms Comparison
The following focus test result shows the comparison of 50ms and 80ms. This test
 reflects the smart contract performance by the success rate of executing a `for` loop in the smart contract. 

![image](https://user-images.githubusercontent.com/70734475/114877787-33d3bd00-9e32-11eb-80ea-41a11684d12a.png)

Through the data, we can find that in the case of 50ms, the maximum number of `for` loops that can be executed is around 13,200. After increasing to 80ms, there is still a 22% success rate of executing 25,000 times `for` loops.

Welcome to discuss.

**Comment by dkealervdsf** [comment] 2021-04-16 07:26
I know that there is no transaction time limit for Ether, why does Tron have to limit it? And why is it set to 80ms, is there any basis?

**Comment by Omo-Coc** [comment] 2021-04-18 15:10
> I know that there is no transaction time limit for Ether, why does Tron have to limit it? And why is it set to 80ms, is there any basis?

At present, there are not many contracts over 50ms in the entire network. it should not be increased a lot at one time, because if there are too many contracts with high complexity in the entire network, it will Affect TPS.Just increase them appropriately. After the increase to 80, they can be increased again as needed.

**Comment by jamestompson** [comment] 2021-04-19 03:43
Very good proposal, and gives the data feasibility, hope to adopt soon

**Comment by joker-gdb** [comment] 2021-04-20 08:06
It should have been improved a long time ago, currently 50ms limits a lot of scenarios

**Comment by Omo-Coc** [comment] 2021-04-22 09:29
Regarding this issue, I think java-tron should solve the problem of out-of-time in simple transactions ASAP. For example, I have encountered out-of-time in USDT transfer transactions before, which caused me to lose 5000 TRX.

Obviously this is not caused by the high complexity of the contract. Can anyone tell me why?

**Comment by Benson0224** [comment] 2021-04-22 10:03
> Regarding this issue, I think java-tron should solve the problem of out-of-time in simple transactions ASAP. For example, I have encountered out-of-time in USDT transfer transactions before, which caused me to lose 5000 TRX.
> 
> Obviously this is not caused by the high complexity of the contract. Can anyone tell me why?

First of all, we are really sorry to hear about your loss, and we will pay more attention to the problem you mentioned.

**Comment by otakuinny** [comment] 2021-04-23 06:48
> Regarding this issue, I think java-tron should solve the problem of out-of-time in simple transactions ASAP. For example, I have encountered out-of-time in USDT transfer transactions before, which caused me to lose 5000 TRX.
> 
> Obviously this is not caused by the high complexity of the contract. Can anyone tell me why?

How did you lose 5000 trx as a result of a failed txn? Are you sure you didn't lose it to something else?

**Comment by Omo-Coc** [comment] 2021-04-25 06:01
> > Regarding this issue, I think java-tron should solve the problem of out-of-time in simple transactions ASAP. For example, I have encountered out-of-time in USDT transfer transactions before, which caused me to lose 5000 TRX.
> > Obviously this is not caused by the high complexity of the contract. Can anyone tell me why?
> 
> How did you lose 5000 trx as a result of a failed txn? Are you sure you didn't lose it to something else?

Because my feelimit is set to 5000trx

**Comment by otakuinny** [comment] 2021-04-27 05:14
> > > Regarding this issue, I think java-tron should solve the problem of out-of-time in simple transactions ASAP. For example, I have encountered out-of-time in USDT transfer transactions before, which caused me to lose 5000 TRX.
> > > Obviously this is not caused by the high complexity of the contract. Can anyone tell me why?
> > 
> > 
> > How did you lose 5000 trx as a result of a failed txn? Are you sure you didn't lose it to something else?
> 
> Because my feelimit is set to 5000trx

Set it to a smaller value. Problem solved.

**Comment by call-me-nobody** [comment] 2021-04-27 06:55
This discussion has been going on for a while, and the results show that the communities are in favor of this proposal, 
so based on this, the voting request is expected to be launched on May 7, 2021.

Before the voting request started, welcome everyone to continue the discussion here if you have more opinions.

**Comment by Benson0224** [comment] 2021-05-10 07:10
close this Proposal as it is already passed in mainnet.  Check detail at: https://tronscan.org/#/proposal/61

**Closed by Benson0224** 2021-05-10 07:10 UTC
