### ISSUE TITLE
(new)TRC205: Freeze TRX tokenization #205

### ISSUE THREAD

**Issue by xq-lu** [tronprotocol/tips#236] opened 2021-02-09 07:41 UTC
## Simple Summary
This TIP provides freeze TRX tokenization for java-tron. 

## Abstract
In the current Tron ecosystem, freezing TRX gets bandwidth or energy, and our survey found that the vast majority of TRX holders, rarely use energy or bandwidth, but usually just for voting. However, pledging a large amount of TRX just for voting would obviously lose the right to use TRX, as this would only yield a portion of the voting revenue, which is currently only about 9% to 10% annually. Except for this part of the voting revenue, as a TRX holder, these pledged TRX can't do anything.

Currently, in the TRON ecosystem, lending mining pools are earning [around 7%~12% APR](https://sun.io/#/sun)﻿. If you load the previous vote's earnings with this part of the borrowed mining earnings, then the earnings of pledged TRX will reach 15%~20%. The new scheme can undoubtedly bring a tangible increase in revenue for TRX holders.

Therefore, this freeze TRX tokenization scheme has several purposes: 1. so that TRX holders do not lose the right to use the amount of TRX by pledging TRX. The new tokens can be exchanged and transferred as TRX equity certificates, and the new tokens can be exchanged for the pledged TRX. 2.Increase the revenue of TRX users, in addition to the previous voting revenue, pledging new tokens sent by TRX can participate in pool mining to gain liquidity revenue 

## Motivation
Flexible TRX usage and increase revenue for TRX holders, while ensuring the health and stability of the Tron network.

## Rationale
freezeBalance: Freeze a certain amount of TRX, get the corresponding bandwidth/energy/voting rights, and get a certain number of tokens/vouchers issued by the Tron system
unFreezeBalance：when user returns a certain number of tokens, clear the corresponding amount of bandwidth/energy/voting rights, and returns a TRX for the number of accumulated earnings
transferAssets: User can transfer these TRC10 tokens to each other

## Technical Specifications：
The TRC10 tokens are TRX equity certificates and can be used to receive the corresponding staking TRX proceeds upon unfreezing with the TRC10 tokens.

The TRC10 tokens can be transferred and exchanged with each other.

The TRC10 tokens can participate in mining pool mining to obtain liquidity gains.

The TRC10 tokens can be exchanged with each other with a fixed exchange ratio

The TRC10 tokens  are valued, partly from the exchangeable TRX and partly from other proceeds

 

In order to achieve the desired characteristics above, we propose two solutions:

**Solution 1:**
When the user freezes TRCX, a certain number of such tokens are issued, and the new TRC10 tokens themselves do not come with earnings. The revenue mentioned here refers to the voting revenue gained during the period when the user pledges the TRX, and the user's new TRC10 token balance is increased or decreased by a certain percentage when the user freezes and unfreezes it

The total amount of newly issued TRC10 tokens is fixed, and the exchange ratio is also linked to the amount of TRX pledged.

When the user wants to release the pledge, he/she needs to return the corresponding tokens/vouchers to be able to release the pledge.

 

The specific technical solution is as follows:

1. The exchange ratio between token value and TRX value can be designed as a dynamic exchange, fixed ratio exchange

Fixed ratio exchange: There are three options, which can be designed as 1:1, 1:10, 1:100 with Trx exchange ratio;

Dynamic ratio exchange: can be positively correlated with the amount of user Trx pledge, the more the user pledge Trx amount, the more new token will be obtained. A specific dynamic exchange ratio can be found in the following table.

user staking amount | ratio to TRX
-- | --
0~1000 | 1:1.0
1000~10000 | 1:1.1
10000~100000 | 1:1.2
100000~1000000 | 1:1.4
1000000~10000000 | 1:1.6
10000000~100000000 | 1:1.8
1000000000~1000000000 | 1:1.9
1000000000~ | 1:2.0

The above redemptions are incremental in accordance with the user's pledge volume gradient.

 
Revenue Model：
![image](https://user-images.githubusercontent.com/72730944/107330347-64bf0b00-6aec-11eb-9906-5584c86eebef.png)
Note: The above data are not promised reward rate, need to check it out in the real system operating environment.

**Solution 2:**
The user freezes the TRX and also issues the corresponding number of such tokens, but this TRC10 token comes with a revenue, i.e. the value of the new token is tied to the pledged TRX and the voting revenue during the pledge period.

 

The technical implementation is as follows:

1. When freezing TRX, add the corresponding number of TRC10 tokens TRX-S (TRX-Shadow) to the user's account, currently set at 1 to 1 exchange between TRX and TRC-S

2. When transferring TRX-S, adjust/increase/decrease the amount of TRX-S in both accounts.

3. When transferring TRX-S, adjust/increase the amount of pledged TRX in the accounts of both parties and increase/decrease the corresponding amount of energy/bandwidth/votes. Also, the amount of voting revenue to be withdrawn is adjusted at the same time.

4. When unfreezing TRX, a certain amount of TRX-S will be deducted and the system will return the corresponding amount of TRX to the user's account (the amount of pledged TRX + the voting revenue during this period)

 
The exchange relationship between new TRC10 tokens and TRX:

Since we position the new TRC10 tokens as the equity credentials of pledged TRX, simply understand that the new TRC10 tokens are the shadow of TRX, the solution is that after pledging TRX, we can't do anything else with TRX except voting, which leads to a huge amount of TRX sleeping in pledge, just for voting, at the expense of its most important right of use

So, when you freeze, you freeze 1 TRX and get 1 new TRC10 token. However, the new TRC10 token, after the freeze, is increasing in value. Here, not counting the liquidity gain from the new TRC10 tokens participating in mining pools, after the user pledges TRX, itself is able to get the accumulated voting gain, this part of TRX plus voting gain, its value is mapped above this new TRC10 token, so, when transferring new TRC10 tokens between users, or when unfreezing TRX, the TRX that can be exchanged is an uncertain value.

New TRC10 token value == pledged TRX + pledged trx voting revenue + mining pool mining liquidity revenue

 

### Compare the two scenarios above:
Both of the above scenarios have the same point of minting a fixed number of new TRC10 tokens when TRX is frozen, this number of tokens is strictly fixed and strictly linked to the number of TRX. Therefore, they both have value.

Both two options are essentially aimed at empowering TRX holders and adding additional revenue to their holdings. The specific options adopted differ.

Option 1 is relatively easy to implement, the new tokens themselves do not come with earnings, only as equity certificates, the specific withdrawal of earnings requires the user to operate separately to withdraw earnings operation. Users can take the newly issued TRC10 tokens to participate in the mining pool liquidity mining and get liquidity income.

Option 2 is relatively complicated to implement. The new token itself comes with revenue, which can be understood as a shadow coin holding TRX. This new token can be transferred and exchanged with TRX because it comes with revenue.
## Data Structures：
main parameters of the new insurance token:

"id":"1234567"
"owner_address":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"name":"0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"abbr": "0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"total_supply" :1000000000000,
"trx_num":1,
"num":1,
"precision":1,
"start_time" : 1530894315158,
"end_time":1533894312158,
"description":"007570646174654e616d6531353330363038383733343633",
"url":"007570646174654e616d6531353330363038383733343633",
"free_asset_net_limit":10000,
"public_free_asset_net_limit":10000,
"frozen_supply":{"frozen_amount":1, "frozen_days":2}
}'
## Implementation
coming soon

## Copyright
All content herein is licensed under Apache 2.0.

**Comment by otakuinny** [comment] 2021-02-09 23:54
I applaud that you took time to come up with all this. But freezing TRX and receiving voter rewards at 6-8% APR is already attractive enough. We don't need another token that is created out of thin air to artificially increase the value of TRX. Freezing TRX means just that. Anyone freezing TRX knows full well they can't use them until they are unfrozen.

**Comment by bondibox** [comment] 2021-02-21 23:10
Since the latest fee increase, CPU timeout errors have increased and range from 9,000 to 38,000 errors per day. It is relevant to this proposal because many users are unable to close their justlend contract transactions, as the process steps through every coin they have as collateral. This is an issue that does not surface in nile or shasta testnet because they simply do not have the volume or comparable CPU load.

Until and unless TRON can address the timeout issue and fix justlend, I am vehemently opposed to any new escrow type swap or exchange.

**Comment by xq-lu** [comment] 2021-02-24 09:17
> I applaud that you took time to come up with all this. But freezing TRX and receiving voter rewards at 6-8% APR is already attractive enough. We don't need another token that is created out of thin air to artificially increase the value of TRX. Freezing TRX means just that. Anyone freezing TRX knows full well they can't use them until they are unfrozen.

thanks for your reply.

**Comment by xq-lu** [comment] 2021-02-24 09:32
> testnet

thanks,bondibox。much appreciate for point out this issue. we have already investigated this issue, any updates we will keep you updated:)

**Comment by KI5FPL** [comment] 2021-03-04 12:10
> Since the latest fee increase, CPU timeout errors have increased and range from 9,000 to 38,000 errors per day. It is relevant to this proposal because many users are unable to close their justlend contract transactions, as the process steps through every coin they have as collateral. This is an issue that does not surface in nile or shasta testnet because they simply do not have the volume or comparable CPU load.
> 
> Until and unless TRON can address the timeout issue and fix justlend, I am vehemently opposed to any new escrow type swap or exchange.

I totally agree with @bondibox .

TRON should simplify and unify its implementation, instead of adding more and more to built-in transaction types.

Your "freeze for some token" can also be implemented by routine airdroping. why not?

OUT_OF_TIME should be removed. since java is an GC language, simple transactions can also timeout while an SR doing GC. This type of error frustrats so many users.

**Comment by bondibox** [comment] 2021-03-04 12:24
> OUT_OF_TIME should be removed. since java is an GC language, simple transactions can also timeout while an SR doing GC. This type of error frustrats so many users.

[While GC is an issue in its own right](https://github.com/tronprotocol/java-tron/pull/3637), I believe the OUT_OF_TIME errors are being caused by the problems created by OUT_OF_ENERGY transactions.

**Comment by otakuinny** [comment] 2021-03-05 01:30
I thought an OUT_OF_TIME error occurs when a call takes longer than 50ms. Assuming this 50ms is a configurable value, this can be fixed by just increasing it.

**Comment by joshh71390** [comment] 2021-11-09 05:45
The reason it is called freezing with a three day cooldown period is because it ensures stability... obviously people cant just take all of their money and put it into a savings account because then they cant pay their bills... thats why its there. to freeze your stake and remove it from circulation.

**Closed** 2023-06-13 09:37 UTC
