### ISSUE TITLE
Reward SRs with the transaction fees charged for bandwidth and Energy

### ISSUE THREAD

**Issue by renchenchang** [tronprotocol/tips#196] opened 2020-11-12 09:58 UTC
## Background:
With the development of the TRON network, the TRON network ecosystem has become increasingly prosperous. At the same time, SR (Super Representatives) also need to consume more resources to maintain the entire network, which includes higher hardware demand and higher maintenance cost. The current rewards given to each SR include 16 TRX for block production and 160 TRX for voting. Compared with other public blockchains, the TRON network currently lacks the mechanism for rewarding SR with transaction fees. The transaction fee of the TRON network is mainly caused by energy and bandwidth consumption. Currently, all the transaction fee is transferred to the black hole account.

## Inflation comparison
EOS: 1%
ETH: 4.2%
TRX: 1.6% (without transaction fee reward)
TRX: 1.85%(with transaction fee reward)

TRON inflation is far lower than Ethereum.

## Motivation:
In order to further improve the stability and efficiency of the TRON network, it is proposed to increase the rewards for SRs. The transaction fees charged by energy and bandwidth consumption can be rewarded to SR, and they are distributed to voters like rewards for producing block. Transaction fees will increase the enthusiasm of SR to maintain the network. At the same time, the transaction fee mechanism can effectively prevent SR from producing blank blocks that contain 0 transactions.
## Present condition of transaction fees
These days, there will be 2,000,000 transactions and $17000 fee every day on average. It means every transaction will cost $0.0085 and SR will be rewarded $0.6 for producing a block if SR can package 70 transactions into a block. If transaction fees increase, the fee reward to SR will be very considerable. On the other hand, transactions will decrease if transaction fees increase. We also analyze transaction value distributions. Take USDT for example, 53.6% of USDT transaction values are more than $100, 28.4% of USDT transaction values are more than $1 and less than 100$, only 18% of USDT transaction values are less than $1. So it has only a little effect on transactions if transaction fees increase.

## Reasonable solutions:
Reasonable solutions are as follows:
1. Real-time reward method: Each time the SR produces a block, the transaction fee in the block is rewarded to the SR.
2. Average reward method: After N blocks are produced in the network, the transaction fees in these N blocks are evenly rewarded to SRs, which can prevent SR from only packaging transactions with higher fees.
## Note:
For the fees of timeout smart contract transaction, it should continue to transfer them to the black hole account to avoid malicious SRs from deliberately setting the transaction overtime to obtain high fees.

**Comment by Imbaexchange** [comment] 2020-11-13 07:49
higher rewards will only dump the price more and more what effect that no one will earn more.

its a simple calculation when you put daily 4.5 million TRX in the Market and the demand is growing low, the price will go down.

ETH show us how it work. high fees, high demand, low inflation. Price go up the community is happy, price go up more. 
Now ETH want to go to PoS and reduce the inflation again.

Why not reduce the rewards until there is not more demend. so the price will go up and SR will earn more.

**Comment by behilter** [comment] 2020-11-13 07:56
This is attractive for SR, but it is not friendly for ordinary TRX holders.

**Comment by tronfamily** [comment] 2020-11-16 08:59
Higher server costs can also be covered by other means. For example, by lowering the rewards to the voters.

A distribution of 80% of the rewards to the voters leaves enough room for a very good node, which costs on average $100 per month. To cover the costs at the current TRX price, a daily rate of block rewards from a single SR is sufficient.

17,066 TRX per day x $0.025 = $426.65 per day.

The proposal is unacceptable for us, because it increases inflation and the gap between SR (1-27) and SRP(28-127) is much wider.

**Comment by fbsobreira** [comment] 2020-11-16 16:47
1 - The current rewards for ELECTED SR (top 27) sharing 90% with supported is enough to maintain 2 or even 3 very reliable servers and also have few buckets extra for some promotion from time to time.
2 - Most of SRs shares 80%, or even 0% in some cases, meaning they have enough room to maintain a very reliable infrastructure for Tron Network, especially if TRX price increases (that's what we all hope)
3 - Rewards per transactions packed will not prevent current elected SRs to produce blocks with 0TX. Penalty for not do the correct job is possible a more efficient solution.
4 - The USDT taken as example is misleading. Tron is know for heaving cheap, reliable and fast transactions, most of the tokens in Tron's blockchain generates transactions with a lot less then $1. We can scrap the numbers, but don't think will be needed.... For what I see the discussion is not to raise fees, but actually redirect to SRs instead of BURN.... so no gain in comparing it with TX value transferred.
5 - This could lead for SRs to modify node in order to only pack payable TXs (no bandwidth or energy expended but actually TRX), or even an easy way by giving priority to bigger TX or know contract with more fees.
6 - When we have the block/votes rewards changed a while back, we hope that someday fee burned with TX (essentially from energy) would make TRX a deflationary cryptocurrency and the changes proposed in this discussion takes the other way around.

**Comment by kunlunxuejue11** [comment] 2020-11-17 03:49
In order to reduce inflation, I would suggest we increase the transaction fee, and this will leads to more TRX burn, would be helpful on inflation.

**Comment by Hei-jialun** [comment] 2020-11-17 04:02
I'm afraid the only people who will profit from this proposal are the SR and Justin.

Inflation, which TRON criticizes, will be worse and the interests of a large number of ordinary holders will not be protected.

It is rather shameful for the official to sacrifice the interests of the majority to please SR.

As a TRX holder, we strongly disagree.

**Comment by renchenchang** [comment] 2020-11-17 04:46
> I'm afraid the only people who will profit from this proposal are the SR and Justin.
> 
> Inflation, which TRON criticizes, will be worse and the interests of a large number of ordinary holders will not be protected.
> 
> It is rather shameful for the official to sacrifice the interests of the majority to please SR.
> 
> As a TRX holder, we strongly disagree.

beside SR, voters can also share the reward

**Comment by renchenchang** [comment] 2020-11-17 04:56
Voters can share the transaction fees like reward for voting SR, so I think more voters will freeze TRX to get the reward. Maybe it has no affect on Inflation.

**Comment by tronfamily** [comment] 2020-11-17 05:30
What if the nodes only produce money-making transactions and others are thrown back? For example, the transactions created with free bandwidth or energy?

This would result in prioritization or ultimately only TRX burnt transactions. Bandwidth and energy would be discarded.

**Comment by Hei-jialun** [comment] 2020-11-17 06:09
> Voters can share the transaction fees like reward for voting SR, so I think more voters will freeze TRX to get the reward. Maybe it has no affect on Inflation.

Compared to those who vote to participate, those who don't vote are in the majority. And how do you address the resulting inflation.

**Comment by Hei-jialun** [comment] 2020-11-17 06:15
Another questioin:
If SR do something bad, for example, change the code to make smart contract related transactions to timeout, then they can get the fee limit. Is that right?

**Comment by behilter** [comment] 2020-11-17 06:17
> > Voters can share the transaction fees like reward for voting SR, so I think more voters will freeze TRX to get the reward. Maybe it has no affect on Inflation.
> 
> Compared to those who vote to participate, those who don't vote are in the majority. And how do you address the resulting inflation.

I can not agree with your more.

**Comment by renchenchang** [comment] 2020-11-17 06:19
> Another questioin:
> If SR do something bad, for example, change the code to make smart contract related transactions to timeout, then they can get the fee limit. Is that right?

For the fees of timeout smart contract transaction, it should continue to transfer them to the black hole account

**Comment by zweryok** [comment] 2020-11-17 09:32
Raising the price for the end user is not acceptable.
Paying SR commissions instead of burning will result in higher emissions and lower prices, after which SR will demand even more.
You say the problem is loading, so let's solve the problem of loading. I have two solutions:

1. Let's create another "batch" of 27 SRs. There was one batch of 27 SR, there will be two, each of 27 SR. The transaction will be translated into a less loaded package. At the same time, some semblance of monopoly will disappear: new nodes will have motivation, old ones will cease to be greedy.

2. Add 3 levels of SR: the first level - gold 27 SR - gets 8 trx per block, the second level - silver 27 SR - gets 5 trx per block and the third level - copper 27 SR - gets 3 trx per block.

**Comment by git2702** [comment] 2020-11-17 09:38
As an SRP we are against it as it would result in more going to SRs which are largely made up of TRON nodes. 

As SRPs we have no chance of ever competing with these nodes we can't afford to "buy a seat". We really want to continue promoting Tron and bringing back the community but it's difficult when we are not making any money to cover costs

**Comment by cryptoguyinza** [comment] 2020-11-17 09:51
Hi

Transaction fees are a way to reduce trx supply or slow down the trx supply from increasing. I think keeping this in play is best.

Ideally we would like transactions fee costs to increase a bit more and also bring more use cases so transaction fees hopefully is greater than new trx generated. So I would prefer to not have transaction fees come to SR.

I do not think SR need more rewards at this stage. If we want a SR to spend more on hardware rather try other approaches like
- apply a max share % with voters across all SR on the tron automatic reward collection.  
- make block rewards higher, failure to run a good node will mean missed blocks and less rewards

These are some ideas.

**Comment by zweryok** [comment] 2020-11-17 10:00
The higher the transaction cost, the lThe higher the transaction cost, the lower the availability. The lower the availability, the fewer people = lower popularity, correspondingly weaker competitiveness with other blockchains.ower the availability. The less availability, the fewer people.

**Comment by simbadMarino** [comment] 2020-11-17 12:25
If approved that will be unacceptable, TRX burning is giving the price a little bit of hope for investors to be stable in the long term otherwise we are getting diluted even more. Please do not accept this kind of greed and short sighted incentives!! Totally unacceptable!!

**Comment by TronSpark** [comment] 2020-11-17 14:14
Problem: 
SRs may not put in place the necessary resources to successfully support a robust and growing network.

The root cause of the issue we have is due to the voter reward culture(reward for vote) that is already established. We can't change that. Therefore, increasing overall rewards will not benefit the SR. In fact, we increased rewards from 32 TRX to 176 TRX yet most of that went right back to the community and not the SR. SRs are now making less TRX than they were a year ago. Yet, the resources needed is growing as the network expands. Also, shifting the ratio between block rewards and voter rewards will get much objection from voters. Therefore, we support SR transaction fees as it helps SRs operate reliably without the pressure from voters wanting higher rewards. There has always been a conflict of interest between network integrity and voter rewards.

Some are worried about devaluation. The inflation we are talking about is not significant. In a growing crypto environment, where we expect the masses to adopt the technology, it should be practically negligible. The onboarding of new customers should very easily overcome this pressure. We went from 32 trx per block to 176 trx per block and the TRX price didn't suffer. We do need a robust network if Tron plans to remain a leader.

**Comment by simbadMarino** [comment] 2020-11-17 16:52
As a TRX voter and holder I would not care to take a cut in the voting rewards but still consider the fees should go to the burning mechanism. I think most of  us will be happy to share some voting rewards to SRs instead of this, fee burning is a direct “reward” for the whole ecosystem as we increase Tron usage and adoption, if you remove that you are killing lots of trust from investors. If current SRs are no longer profitable and cannot find another solution  maybe it’s time for new SR to take their place if they can find cheaper and robust solutions for hosting and servers ;)

**Comment by ibnzUK** [comment] 2020-11-17 19:17
**Possible issue** 

When there is an application where instant execution time is not required, say order submitted or cancelled on exchange running on Tron. Exchange developers can technically submit those transactions on to blocks they want.
The system could become rigged with some nodes doing more work (for their own benefit) and others do less. 

- SR's who redistribute token rewards to voters can adjust their software to only fill blocks with transactions when it is their turn to produce a block. `(example) `

- Dapp developers could choose to ignore particular nodes or in the worst case, Tron Foundation itself could use their own nodes to do all the work needed. 


_

> The example below is just a heavy load of transactions in 6 seconds, but when targeted correctly this could be 3 times more rewards for someone.

_ 

![image](https://user-images.githubusercontent.com/38762355/99436075-e7c72f80-2908-11eb-8cb3-c39d9669d09d.png)

**Comment by bondibox** [comment] 2020-11-17 19:17
It has always been my understanding that the inflation caused by SR rewards is temporary, and eventually SR block and voter rewards will be offset entirely by transaction fees, or actually phased out and replaced by the transaction fees. Unfortunately, current TRON blockchain adoption has resulted in transaction fees which are only about 13% of what would be needed to offset inflation.

Currently, the annual rate of inflation for TRX total supply is about 1.85%. This proposal would add to that another 0.25% for a total of 2.1% annual inflation.

I question the necessity of this proposal. The very last elected SR with only 1% of voter rewards will receive 17,067 TRX in block production rewards, and 46,080 TRX in voter rewards. At the current price of TRX that is approximately **$1,600 USD per day** in SR revenue, and even after sharing 80% of voter rewards is still left with 26,283 TRX or approximately $683, **per day** and $20,500 per month. If the OP is unable to run a TRON node for $20k per month, he's doing something wrong.

Finally I come to the crux of my argument. OP says the motivation for this TIP is <blockquote>In order to further improve the stability and efficiency of the TRON network</blockquote>but that is not what this TIP will accomplish. If SR's are compensated by the number of transactions that are put into a block, then you can expect SR's to funnel transactions toward their own blocks. An SR who is running a dapp will delay transactions from their dapp until they can be included in their own blocks, or the blocks of SR's they support. This will give rise to cliques and cabals of SR's and dapp developers who withhold transactions from being included in the blocks of producers whom they do not support.

**Comment by leenasamme** [comment] 2020-11-18 03:20
who is that asshole posted this proposal, don't face me in front your 32 teeth will be on the road

**Comment by KI5FPL** [comment] 2020-11-18 06:53
You should solve the design flaw of `TIMEOUT` first.
When an SR node is doing GC, with out-dated server, the 50ms timing limit is unfair for dapp users.

Make it a weighted OpCode count solves. Yet you never cares.

**Comment by renchenchang** [comment] 2020-11-19 07:59
> You should solve the design flaw of `TIMEOUT` first.
> When an SR node is doing GC, with out-dated server, the 50ms timing limit is unfair for dapp users.
> 
> Make it a weighted OpCode count solves. Yet you never cares.

unlike ethereum, TRON must produce a block every 3 seconds.

**Comment by Btcrabbit** [comment] 2020-11-19 08:03
I will agree with this proposal if the implementation can promise the rewards are divided by all the voters. Right now, many SRs set the dividend ratio to 0 and the voter can not receive any reward from staking the TRX and voting to SR. So, the most important thing is ensuring the reward is not "stolen" by bad SRs.

**Comment by tronfamily** [comment] 2020-11-19 09:00
However, this no longer matches the motivation of the TIP but feeds the fear that it only serves to enrich the first 27 SR.

If one gives the unburned fees as a reward to the SR's and the SR's to their voters, then again nothing remains for the "hardware costs".

**Comment by tronfamily** [comment] 2020-11-19 09:36
A proposed solution for cost recovery:

Decoupling the block rewards from the onchain rewards. These would no longer be distributed as rewards and remain with the SR for the corresponding hardware costs.
So the scissors will close a little between 1-27 and 28-127. If the SR distributes the block rewards to the voters, it is his own fault.

The fees will still be burned and the problem solved.

**Comment by renchenchang** [comment] 2020-11-19 09:54
> A proposed solution for cost recovery:
> 
> Decoupling the block rewards from the onchain rewards. These would no longer be distributed as rewards and remain with the SR for the corresponding hardware costs.
> So the scissors will close a little between 1-27 and 28-127. If the SR distributes the block rewards to the voters, it is his own fault.
> 
> The fees will still be burned and the problem solved.

Could you explain in detail?

**Comment by tronfamily** [comment] 2020-11-19 10:16
Total Votes Netzwerk: 24,697,752,750

Vote-Reward-Pool
4,608,000 TRX / 24,697,752,750 = 0,000186575 TRX per Vote

Block-Reward-Pool
460,800 TRX / 27 = 17066,67 TRX

Vote Rewards = 350,000,000 * 0.000186575 TRX = 65301,25 TRX
Block Rewards = 17,066 TRX
Total Rewards = 82,367 TRX

Example SR with 350,000,000 votes (with 90% onchain rewards actual)
82,367 TRX / 100 * 90 = 74,130.525 TRX (to the voters)
left: 8,236.475 TRX (SR income)

Example SR with 350,000,000 votes (90% onchain rewards with excluded blockrewards)
65301,25 TRX / 100 * 90 = 58,771.125 TRX (to the voters)
left:

Vote Rewards: 65,301,25 TRX - 58,771.125 TRX = 6,530.125 TRX
Block Rewards:  17,066 TRX
Total SR-Income: 23,596.125 TRX

Overview:

Income with onchain Blockrewards    :   8,236 TRX
Income without onchain Blockrewards:23,596 TRX

**Comment by bondibox** [comment] 2020-11-19 15:02
> Right now, many SRs set the dividend ratio to 0 and the voter can not receive any reward from staking the TRX and voting to SR.

If an SR has a 0 payout _then vote for a different SR_.

**Comment by Omo-Coc** [comment] 2020-11-20 02:43
This proposal will promote more users to freeze and vote in a short time, and more freeze will be more helpful to maintain the currency price

**Comment by tronfamily** [comment] 2020-11-20 05:02
Can you explain why more people freeze and vote through this proposal?

**Comment by joker-gdb** [comment] 2020-11-20 08:40
From the current transaction cost statistics, the impact on inflation is not big，So I think we should not argue about inflation, mainly whether there is a possibility of evil in SR， If there is no possibility, I think this proposal is ok

**Comment by MishaLederman** [comment] 2020-11-22 08:45
Here are Klever.io’s thoughts and ideas regarding the proposal.

Let’s start deconstructing arguments to see how efficient this proposal would be:
1 - Background
Does maintaining the entire network demands lead to higher hardware demand? Yes.
Is the current rewards enough to pay for those cutting edge hardware? Yes, it is more than enough to maintain several nodes.
So, why more rewards? Apparently the cost of hardware has no relation with redirect TX fees to SR block production.
Does other blockchain include TX fees as block production rewards? Yes, but some have fixed max supply (Tron does not), and do we need to do the same thing as others?

2 - Inflation comparison
Is inflation far lower than Ethereum? Yes. Do we need to compare to others again? Why not compare with EOS which already have inflation lower than tron? Ok, Ethereum is a top 2 market cap, but its a 5+ year old blockchain.

3 - Motivation
 Does more rewards, or TX fees to SRs, improve the stability and efficiency of the network? We don’t see any direct relation with it. Code/Protocol improvement would be a better option for those topics
 Transaction fees will increase the enthusiasm of SR to maintain the network!!! Ok, this is possible. We’re sure higher TRX value would also cause the same enthusiasm.
 If TX fees also goes to voters sharing ratio, how would it improve the capacity of SRs to apply better hardware (not that they need that, but its in the background argument)
 TX fee mechanism can effectively prevent SR from producing blank blocks that contain 0 transactions? There are many other ways to effectively prevent this, like SLASH bad SRs, we have been putting this option at SRs/Developers meeting for more than a year now. 

4 - Present condition of transaction fees
   Transaction fees increase only has a little effect on transactions? This is strange, what does Transaction fees increase have to do with the topic in discussion? The proposal is to redirect transactions Fees, not to increase.... Either way... the statement is true for USDT, but MOST of Tron’s transactions is much lower than $1, USDT example is misleading the statement.

5 - Reasonable solutions
   1 - One should be able to pick the best transaction based on the fee to pack, which is not good in Tron’s model. Also, dapps and exchanges would be able to sync TX with predicted slot time to gain higher rewards
   2 - Maybe the best option, but then... the argument of bad SRs with 0 transaction in block will break... those will also receive TX fees even if node is not good enough to produce blocks with transactions
Extra: Its been said in discussions that higher rewards would attract more frozen TRX... Its possible, but what is the gain? Right now exchanges have higher staking participation ,and holders can still dump price in exchanges and receive the sharing rewards... This is likely what we have seen over recent period.

**Comment by a49688448** [comment] 2020-12-07 08:09
I'm curious that who will benefit from this？

**Comment by joker-gdb** [comment] 2020-12-07 08:21
> I'm curious that who will benefit from this？

I think SR will be the direct beneficiary, but SR will need to hold trx for a long time. The province bears the risk of trx price fluctuations, and it should increase their income.

**Comment by a49688448** [comment] 2020-12-08 03:25
> > I'm curious that who will benefit from this？
> 
> I think SR will be the direct beneficiary, but SR will need to hold trx for a long time. The province bears the risk of trx price fluctuations, and it should increase their income.

I have nothing to do with it as I am not a SR.

**Comment by joker-gdb** [comment] 2020-12-08 06:31
> > > I'm curious that who will benefit from this？
> > 
> > 
> > I think SR will be the direct beneficiary, but SR will need to hold trx for a long time. The province bears the risk of trx price fluctuations, and it should increase their income.
> 
> I have nothing to do with it as I am not a SR.

Voters will also be given rewards, and you will also get benefits, you can see the introduction in Motivation. May be prorated to sr voters

**Comment by a49688448** [comment] 2020-12-09 03:53
> > > > I'm curious that who will benefit from this？
> > > 
> > > 
> > > I think SR will be the direct beneficiary, but SR will need to hold trx for a long time. The province bears the risk of trx price fluctuations, and it should increase their income.
> > 
> > 
> > I have nothing to do with it as I am not a SR.
> 
> Voters will also be given rewards, and you will also get benefits, you can see the introduction in Motivation. May be prorated to sr voters

Yeah. It does attract more people to vote and freeze TRX for rewards.

**Comment by liankuaiZyumingfit** [comment] 2020-12-11 08:15
Looks cool～

**Comment by git2702** [comment] 2020-12-11 08:58
If this is to be spread amongst the 127 SR / SRP then it could be a good thing and would encourage competition but if it is just the 27 SRs (which the majority are Tron owned nodes) then it just gives more reason for Tron to just buy every SR place

**Comment by Omo-Coc** [comment] 2020-12-11 09:52
Rewards can be distributed to voters, this  is a very good change

**Comment by tronfamily** [comment] 2020-12-11 11:14
I don't know why they write that the voters benefit. Wasn't this TIP about covering the cost of the node and infrastructure?

So not after all? It seems that it is not yet clear what the purpose is.

For anyone who wants to see a preview of what this will look like in the end, feel free to take a look here: https://tron-radar.de/profit.html.

You will quickly notice that this has nothing to do with covering costs. It's all about profits.

Only SR 1-27 will profit from this proposal, the others will lose more. Who will take these places in the future should be clear to everyone.

**Comment by kunlunxuejue11** [comment] 2020-12-17 07:09
> I don't know why they write that the voters benefit. Wasn't this TIP about covering the cost of the node and infrastructure?
> 
> So not after all? It seems that it is not yet clear what the purpose is.
> 
> For anyone who wants to see a preview of what this will look like in the end, feel free to take a look here: https://tron-radar.de/profit.html.
> 
> You will quickly notice that this has nothing to do with covering costs. It's all about profits.
> 
> Only SR 1-27 will profit from this proposal, the others will lose more. Who will take these places in the future should be clear to everyone.

I think their purpose is to promote more people to freeze trx

**Comment by bondibox** [comment] 2020-12-17 15:55
> > I don't know why they write that the voters benefit. Wasn't this TIP about covering the cost of the node and infrastructure?
> > So not after all? It seems that it is not yet clear what the purpose is.
> > For anyone who wants to see a preview of what this will look like in the end, feel free to take a look here: https://tron-radar.de/profit.html.
> > You will quickly notice that this has nothing to do with covering costs. It's all about profits.
> > Only SR 1-27 will profit from this proposal, the others will lose more. Who will take these places in the future should be clear to everyone.
> 
> I think their purpose is to promote more people to freeze trx

But to what end? They say it's for stability and governance blah blah blah. But the vast majority of frozen TRX is coming from exchanges and TRON / Justin - are they really worried about stability and governance? Is there any possible way someone could install 19 SR's to overtake consensus? Is there any way a proposal can pass without being promoted by TRON & Justin? I think this line that more freezing is essential to TRON stability is just more s-- they are throwing at the wall to see what sticks, just like paying for hardware or rewarding the voters. Just more gaslighting from TRON.

**Comment by GitHub-pepe** [comment] 2020-12-21 08:14
Reward SRs with the transaction fees charged for bandwidth and Energy #196

**Comment by tomasvalero** [comment] 2021-01-11 20:55
It is true that SRs should make profitable production costs per block, but the solution being promoted makes the continuous burning of coins impossible.
 In fact, if there were a continuous burning, above production, it would objectively imply a rise in the price of Trx and the SRs could be paid for with the current reward system. On the other hand, an inflationary increase could cause massive sales of Trx, falling its  price and that not even the increased rewards could cover the costs of the SRs.
 Perhaps an increase in rewards per block creation and a small increase in transaction fees on the blockchain would be more appropriate than the solution presented here.

**Comment by sean-liu55** [comment] 2021-01-12 07:55
https://github.com/tronprotocol/tips/blob/master/tip-196.md

**Closed by sean-liu55** 2021-01-12 07:55 UTC

**Comment by kromulan** [comment] 2021-01-19 09:19
SR's do not require more rewards. If current rewards are not enough to run infrastructure, you are doing something wrong.

**Comment by zweryok** [comment] 2021-01-19 09:32
Read my version. SR tokenization
https://github.com/tronprotocol/tips/issues/221

**Comment by vantwoutmaarten** [comment] 2021-01-19 10:57
How can I see if there are SR's voting for this? Because I want to withdraw my votes for them. I have a lot of votes so someone please let me know?

It's just greedy shortsighted SR's that want this. This will not benefit them in the end.

**Comment by vantwoutmaarten** [comment] 2021-01-19 10:58
> I'm afraid the only people who will profit from this proposal are the SR and Justin.
> 
> Inflation, which TRON criticizes, will be worse and the interests of a large number of ordinary holders will not be protected.
> 
> It is rather shameful for the official to sacrifice the interests of the majority to please SR.
> 
> As a TRX holder, we strongly disagree.

Justin is against this.

**Comment by bibobode** [comment] 2021-01-19 17:50
Take a look at **[Nano](https://www.nano.org)** - it has a feeless network, instant transactions, decentralized, and been running successfully since 2015.

**Comment by bondibox** [comment] 2021-01-19 20:06
If you believe Justin is against this then you have been selected to send up to 100 BTC to the following address and I will send back DOUBLE what you sent me...

Are we really supposed to believe that Tron Foundation slipped in tests like
"Test deploy contract with energy fee to sr"
"trans with multi sign and fee to sr"
"Test create account with netFee to sr"

and a parameter getAllowTransactionFeePool

And this was all against Justin's wishes? Or it was unbeknownst to him? Great. Either he's gaslighting us, or the company he's running has gone rogue.
