### ISSUE TITLE
TRC-247 : Tron Hybrid consensus

### ISSUE THREAD

**Issue by lvs007** [tronprotocol/tips#247] opened 2021-03-23 02:50 UTC
```
tip:  247
title:  Tron Hybrid consensus
author: xing@tron.network
status: Draft
type: Standards Track
discussions to: https://github.com/tronprotocol/tips/issues/247
category: Core
created: 2021-03-23
```
## Simple Summary
 
The widely used pBFT consensus can shorten confirmation time and improve TPS, which leads to some top blockchain companies starting to introduce and implement it. Based on TRON‘s previous DPoS consensus, an optimized version of pBFT combined with TRON DPoS consensus provides better performance and expands the TRON ecosystem like cross-chain project that uses TRON hybrid consensus for block verification.
This TIP mainly describes the new TRON hybrid consensus algorithm and explains how it works on the TRON blockchain. In addition, this tip will talk about a comparison between old TRON consensus and the new hybrid consensus algorithms.
 
## Abstract
 
Practical Byzantine Fault Tolerance is a consensus algorithm used in asynchronous distributed systems that keeps the entire distributed system available on the condition of partition failure. Besides, pBFT can provide a global consensus state between different nodes, which is highly demanded in blockchain. By tailoring pBFT message types, hybrid TRON consensus only requires three types of pBFT messages; it combined with DPoS, gives a better performance and shrinks block confirmation time to only 1 or 2 slot time on average.
 
## Motivation
 
In the current DPoS consensus mechanism of TRON Protocol, the average confirmation time for one block is equal to (2/3 * Number of SRs) slots. With the adoption of pBFT consensus algorithm, the confirmation time will shrink significantly to only 1 or 2 slot times if the network environment is good enough. In addition, the newly TRON hybrid consensus can always provide solidity block header information for query, so is no unconfirmed state block in the newly hybrid pBFT chain. In this scenario, cross-chain and SPV can be implemented by querying valid block header information from pBFT chain built on hybrid TRON consensus.
 
### Node
 
- SR(Super representative): nodes that produce blocks
- Verifier: nodes that trigger the pBFT consensus procedure for blocks produced by SRs
- Full node: normal nodes that supervise the consensus behavior above
 
### Message type in
 
![pbft-1](https://user-images.githubusercontent.com/33735949/112411988-b9df7500-8d58-11eb-87c1-af5a75c38eb8.png)
pBFT
                         <center> Figure 1 </center>
 
 
 
- VIEW_CHANGE: usually happen when primary replica fails
- REQUEST:  client send a request to primary replica
- PRE_PREPARE: other replicas receive message from primary replica
- PREPARE: receive multicast pre_prepare message
- COMMIT:  receive multicast prepare message
 
### Message type in TRON hybrid consensus
 
- PRE_PREPARE : will be generated while processing receiving blocks (SR)
- PREPARE :  will be generated once done with processing blocks (SR)
- COMMIT :  will be generated once Verifiers receive 2/3+1 valid signed prepare messages (Verifier)
 
 
## Rationale
 
Normally,there are `request->Pre-prepare->prepare->commit->reply`  five types of messages on pBFT , but with optimized TRON pBFT , there are only `pre_prepare->prepare->commit` three types of messages, which is much easier to manipulate and implement.The optimized consensus, which combines the current TRON consensus algorithm, has three phases; the first phase is block broadcasting, which is equivalent to the pre_prepare phase of traditional pBFT; the second phase is the voting stage where blocks are verified, equivalent to the prepare phase of traditional pBFT; the third phase is verification of vote results, equivalent to the commit phase of traditional pBFT. Below are the details(SRs can be verifiers too):
1. SRs start to process blocks and generate pre_prepare message
2. Upon receiving the broadcast block, Verifiers will validate it, then sign and broadcast prepare message
3. Upon receiving signed prepare messages from more than 2/3+1 Verifiers, a commit message will be generated, which will then be signed and broadcasted by Verifiers
4. If nodes receive signed commit messages from more than 2/3+1 Verifiers, it is deemed that the current block can never be reverted
 
![pbft](https://user-images.githubusercontent.com/33735949/112591759-d2768a80-8e3f-11eb-8713-d0466562329b.png)
                      <center> Figure 2 </center>
Firstly, SR will take turns to produce and broadcast blocks and generate a pre_prepare message. Secondly, Verifiers alway listen to the channel and monitor if there is a coming produced block, if yes then start to validate and process. Once everything is passed, Verifiers will broadcast a prepared message with their signatures to trigger the pBFT consensus procedure. And then Verifiers also check whether they receive 2/3+1 signed prepare messages in this round, if yes ,and then generate a commit message with their signature and then broadcast it.
 
Such a round of pBFT consensus procedure will be conducted every time when a block is processed. In order to valid block header, their PBFT information will be saved to the local database through `putBlockSignData` function and ready for verification in the lightweight clients.
Each node only votes one time on the same block height; messages already received will be discarded right away. Meanwhile, if the node fails to confirm the prepare messages upon receiving commit messages, the current commit messages need to be cached.
TRON's optimized pBFT consensus algorithm also features a Timeout mechanism. If a round of pBFT algorithm fails to reach finality within a given period of time, all data related to this round will be cleared by all nodes. But one difference from the traditional pBFT is that TRON will not re-initiate this round.
 
- Fork 
 Rule 1: always choose the fork chain which first receives 2/3 +1 Verifiers replicas commit messages as the main chain. Rule 2 : if no block receives 2/3 +1 commit messages, then choose a longer chain as the main chain. Follow priority : rule1 >rule2.
 
 
 
 Threshold signature scheme can help handle multisignature schemes related to the PBFT consensus algorithm. Using threshold signature schemes in the signature module and the verification module will make the entire system simpler and more efficient. Therefore, we plan to utilize this technology in the upcoming versions.
 
Notice: SR can be Verifier
 
 
### Comparison
Basically, adding multiple Verifiers in the current TRON network can shorten the block confirmation time. Current TRON consensuses algorithm always require 2f+1 =19 nodes to confirm a block, which take 19 slot time, while optimized TRON pBFT only requires 2/3+1 verifiers to confirm block, which take less time in comparison with the former one since network request can be handled in few seconds.
Considering the slide windows model, The current TRON consensus algorithm only moves one slot every pass, while optimized TRON pBFT can move multiple slots once receiving 2/3+1 Verifiers replies. Below is current TRON consensus algorithm:
 
```
    TRON window:       start..........................End
     Block     A  ----> B->C...........17..........--->R                    (a)
     Status  solid ---> unconfirmed->...........->unconfirmed
```
Initially, the slide window starts from the first unconfirmed block, the size is 1.Then it will increase window size as the number of unconfirmed blocks increases. Once windows size reaches threshold say 19+1, which is R in above, then make B‘s status solid, move start point into C, decrease windows size by one, which is 19. And continue to move once the start point block of windows becomes solid status.
When combined with optimized TRON pBFT, the windows can move faster.
```
TRON window:     start....................................End
optimized:       start                  end(receives message)              (b)
Block     A  ----> B----->C------>D------>E..............--->R
Status  solid ---> unconfirmed->...................->unconfirmed
```
 
For optimized PBFT, the slide window starts from the first unconfirmed block with size of 1, and it will increase window size as the number of unconfirmed blocks increases when 2/3+1 replies commit messages from verifiers are not received. Once verifiers receive more than 2/3+1 replies commit messages from verifiers stating that block E is valid, which proves that block E on (b) is valid, which draws a conclusion that B,C,D,E are all valid and can be marked as solid status since each block hash was calculated from previous block hash . In this case, the slide windows move super faster in comparison with TRON windows before TRON windows reach thresholds-19. In the best case, which means no fork and network is good means slot time is enough to receive verifier replicas messages, both of them have the same move speed after TRON windows size reached the threshold. However, if there was a fork on the main chain, then TRON window (a) would reset the windows size and wait for another 19 blocks time to confirm while optimizing window (b) can maintain the same moving speed. More details: See the proof of the correctness of optimized pBFT.
Notice: even if (a) and (b) have the same window moving speed, the transaction confirm time of (a) is much longer than (b) since it need to wait for more than 2f+1 block to be produced to valid a block
 
-  more details [Comparison](https://github.com/tronprotocol/tips/blob/master/tip-64.md)
 
 
 
### Data types  
 
`PBFTMessage`: Type indicates the vote message type.
`Raw` indicates the data that needs to be signed, which mainly includes: msg_type, data_type, signature, view_n, data and epoch.
`signature` indicates SR's signature on the entire raw data.
 
```typescript
 
message PBFTMessage {
 enum MsgType {
   VIEW_CHANGE = 0;
   REQUEST = 1;
   PREPREPARE = 2;
   PREPARE = 3;
   COMMIT = 4;
 }
 enum DataType {
   BLOCK = 0;
   SRL = 1;
 }
 message Raw {
   MsgType msg_type = 1;
   DataType data_type = 2;
   int64 view_n = 3;
   int64 epoch = 4;
   bytes data = 5;
 }
 Raw raw_data = 1;
 bytes signature = 2;
}
 
```
 
`PBFTCommitResult` is mainly used to store signed messages.
`Data` refers to the data signed by SRs; `signature indicates SR's signature on data. These two concepts correspond to data and signature in `PbftMessage`.
 
```typescript
 
message PBFTCommitResult {
 bytes data = 1;
 repeated bytes signature = 2;
}
 
```
 
 
### Required functions    
       
Set the signature data of the current epoch SR list. `Cycle` means being currently in that epoch.
 
```typescript
 
public boolean putSrSignData(long cycle, PbftSignCapsule item)
 
```
 
Get the signature data of the current epoch SR list
 
```typescript
 
PbftSignCapsule getSrSignData(long cycle)
 
```
 
Set the signature data of the current block (namely the SR signature list)
 
```typescript
 
public void putBlockSignData(long blockNum, PbftSignCapsule item): 
 
```
 
Get the signature data of the current block (namely the SR signature list)
 
```typescript
 
public PbftSignCapsule getBlockSignData(long blockNum)
 
```
 
Each vote is recorded as a message, so we define a message structure, PbftMessage, to cover all vote messages; please see full details under the data structure.
 
```typescript
 
public class PbftMessage
 
```
 
`PbftBaseMessage` encapsulates PbftMessage and supports features such as signing validation messages and creating prepare and commit messages
 
```typescript
 
public class PbftBaseMessage
 
```
 
`PbftManager`: a function that process different type messages
 
```typescript
 
public class PbftManager
 
```
 
 
`PbftMessageHandle`: a function give implementation of different types of messages
 
 
```typescript
 
public class PbftMessageHandle
 
```

**Comment by spidemen** [comment] 2021-03-23 09:14
update verison: 

```
tip:  247
title: Tron mix consensus
author: xing@tron.network
status: Draft
type: Standards Track
category: Core
created: 2021-03-23
```
## Simple Summary

A widely used pBFT consensus can provide faster confirmation time as well as better TPS, which leads to some top blockchain companies start to introduce and implement it. Based on tron previous DPoS consensus, a modified version of pBFT combined with tron DPoS consensus give a better performance and expand tron ecosystem like cross-chain project uses tron mix consensus for block verification.   
This TIP mainly describes newly tron mix consensus algorithm and give some explanation how it works on tron blockchain. In addition, talk about comparison between old tron consensus and newly mix consensus algorithm.

## Abstract

Practical Byzantine Fault Tolerance is a consensus algorithm used in asynchronous distributed system that keeps the entire distributed system available on the condition of partition failure. Besides, pBFT can provide a global consensus state between different nodes, which is highly demand in the blockchain. By tailoring pBFT message types, mix tron consensus only require three type of pBFT messages, combined with DPoS can give a better performance and shrink block confirmation time to only 1 or 2 slots on average.

## Motivation 

In the current DPoS consensus mechanism of TRON Protocol, the average confirmation time for one block is equal to (2/3 * Number of SRs) slots. With the adoption of pBFT consensus algorithm, however, the confirmation time will shrink significantly to only 1 or 2 slots if the network environment is good enough. In addition, newly tron mixed consensus can alway provide solidity block header information for query, there is no unconfirmed state block in newly mixed pBFT chain. In this scenario, cross-chain and SPV can be implemented by querying valid block header information from pBFT chain built on mixed tron consensus. 

## Specification

### Node 

- SR(Super representative): nodes that produce blocks
- Verifier: nodes that trigger the pBFT consensus procedure for blocks produced by SRs
- Full node: normal nodes that supervise the consensus behavior above

### Message type in pBFT


![](https://github.com/tronprotocol/tips/raw/master/tp/ticp/ticp-optimized-pbft/pbft-1.png)
<center>Figure 1 </center>

- VIEW_CHANGE: usually happen when primary fail 
- REQUEST:  on the stage of client send a request to primary replica
- PRE_PREPARE: on the stage of other replicas receive message from primary replica 
- PREPARE: receive multicast pre_prepare message 
- COMMIT:  receive multicast prepare message

### Message type in tron mixed consensus 

- PRE_PREPARE : will be generated while processing blocks (SR)
- PREPARE :  will be generated once done with processing blocks (SR)
- COMMIT :  will be generated once Verifiers receive 2/3+1 valid signed prepare messages (Verifier)


## Rationale 

Normally,there are `request->Pre-prepare->prepare->commit->reply`  five types of message on pBFT , but with optimized tron pBFT , there are only `pre_prepare->prepare->commit` three types of message, which is much easier to manipulate and implement. By combining with current tron consensus algorithm, the first phase is block broadcasting, which is equivalent to the pre_prepare phase of traditional pBFT; the second phase is the vote stage where blocks are verified, equivalent to the prepare phase of traditional pBFT; the third phase is verifying vote results, equivalent to the commit phase of traditional pBFT. Below are the details(SR can be verifier too):
1. SRs will broadcast the prepare message after producing a block
2. Upon receiving the broadcast block, Verifiers will validate it, then sign and broadcast prepare message
3. Upon receiving signed prepare messages from more than 2/3+1 Verifiers, a commit message will be generated, which will then be signed and broadcasted by Verifiers
4. If nodes receive signed commit messages from more than 2/3+1 Verifiers, it is deemed that the current block can never be reverted

<center>Figure 2</center>

![](https://github.com/tronprotocol/tips/raw/master/tp/ticp/ticp-optimized-pbft/pbft-2.png)

Firstly, SR will take turn to produce and broadcast blocks and generate a pre_prepare message. Secondly, Verifiers alway listen to channel and monitor if there is a coming produced blocks, if yes and start to validate and process. Once everything is passed, Verifiers will broadcast prepare message with their signatures to trigger the pBFT consensus procedure. And then Verifiers also check whether they receive 2/3+1 signed prepare message in this round, if yes and then will generate a commit message with their signature and then broadcast it. 

Such round of pBFT consensus procedure will be conducted every time when a block is processed. In order to valid block header, their PBFT information will be saved to local database through putBlockSignData function and ready for verification in the lightweight clients.

Each node only votes one time on same block height;messages already received will be discarded right away. Meanwhile, if the node fails to confirm the prepare messages upon receiving commit messages, the current commit messages need to be cached.

TRON's optimized pBFT consensus algorithm also features a Timeout mechanism. If a round of pBFT algorithm fails to reach finality within a given period of time, all data related to this round will be cleared by all nodes. But one difference from the traditional pBFT is that TRON will not re-initiate this round.

- Fork  
 
  Rule 1: always choose the fork chain which first receive 2/3 +1 Verifiers replices commit messages as main chain. Rule 2 : if no any block receive 2/3 +1 commit message, then chose longer chain as the main chain. Follow order rule1->No->rule2.

- Other 

  Threshold signature scheme can help handle multisignature schemes related to the PBFT consensus algorithm. Using threshold signature schemes in the signature module and the verification module will make the entire system simpler and more efficient. Therefore, we plan to utilize this technology in the upcoming versions.

Notice: prepare message is included inside block


### Comparison

Basically, by adding multiple Verifiers in the current tron network shorten the block confirmation time. Current tron consensuses algorithm always require 2f+1 =19 nodes to confirm block, which take 19 slot time, while optimized tron pBFT only require 2/3+1 verifiers to confirm blocker, which take less times in comparing with former since network request can be handled by few seconds.
Consider about slide windows model, Current tron consensus algorithm only move one slot every pass, while optimized tron pBFT can move multiple slot once receiver 2/3+1 Verifiers replies. Below is current tron consensus algorithm:
 ```
     Tron window:       start..........................End
      Block     A  ----> B->C...........17..........--->R                    (a)
      Status  solid ---> unconfirmed->...........->unconfirmed
 ```
Initially, slide window starts from the first unconfirmed block, the size is 1, then will increase windows size as the number of unconfirmed block increase. Once windows size reach threshold say 19+1, which is R in above, then make B‘s status to be solid, move into C, decrease windows size by one, which is 19.And continue to move once start point block of windows become solid status.
When combined with optimized tron pBFT, the windows can move faster.
```
 Tron window:     start....................................End
 optimized:       start                  end(receives message)              (b)
 Block     A  ----> B----->C------>D------>E..............--->R
 Status  solid ---> unconfirmed->...................->unconfirmed
```
For optimized PBFT, slide window starts from the first unconfirmed block with size of 1,  will increase windows size as the number of unconfirmed block increase when 2/3+1 relies message from verifiers not be received.  Once get more than 2/3+1 replies messages from verifiers stating that block E is valid, which proves that block E on (b) is valid, which draws a conclusion that B,C,D,E are all valid and can be marked as solid status since each block hash relies precious block hash . In this case, the slide windows move super faster in comparing with tron windows before tron windows reach thresholds-19.  In best case, which means no fork and network is good means a slot time is enough to receive Verifiers replicas, both of them have the same move speed after tron windows size reach threshold. However, if there is a fork on the main chain, then tron window (a) reset windows size and wait for 19 blocks time to confirm while optimized windows (b) can maintenance the same move speed. More detail: See the proof the correctness of optimized pBFT.
  
Notice: even if (a) and (b) have same window moving speed, the transaction confirm time of (a) is much bigger than (b) since it need to wait more than 2f+1 block to be produced to valid a block

-  more details [Comparison](https://github.com/tronprotocol/tips/blob/master/tip-64.md)


## Implementation


### Data types   

Firstly, we need to define a data structure for PBFT signature which encapsulates SR signature data.

```typescript

public class PbftSignCapsule

```

Each vote is recorded as a message, so we define a message structure,
PbftMessage, to cover all vote messages.

```typescript

public class PbftMessage

```

The main aim of this data structure is to save signed commit messages and collect information on SRs who are signing current data.

```typescript

public class DataSign

```

PbftBaseMessage encapsulates PbftMessage and supports features such as signing validation messages and creating prepare and commit messages.

```typescript

public class PbftBaseMessage

```

PbftMessage: Type indicates the vote message type.

Raw indicates the data that need to be signed, which mainly include: pbftMsgType, blockNum, time, publicKey, data and data_sign.

Sign indicates SR's signature on the entire raw data.

```typescript

message PbftMessage {

enum Type {

VIEW_CHANGE = 0;

REQUEST = 1;

PREPREPARE = 2;

PREPARE = 3;

COMMIT = 4;

}

message Raw {

Type pbftMsgType = 1;

int64 blockNum = 2;

int64 time = 3;

bytes publicKey = 4;

bytes data = 5;

bytes data_sign = 6;

}

Raw raw_data = 1;

bytes sign = 2;

}

```

DataSign is mainly used to store signed messages.

Data indicates the data signed by SRs; sign indicates SR's signature on data. These two concepts correspond to data and data_sign in PbftMessage.

```typescript

message DataSign {

bytes data = 1;

repeated bytes sign = 2;

}

```


### Required functions     
         
Set the signature data of the current epoch SR list. Cycle means being currently in that epoch.   

```typescript

public boolean putSrSignData(long cycle, PbftSignCapsule item)

```

Get the signature data of the current epoch SR list

```typescript

PbftSignCapsule getSrSignData(long cycle)

```

Set the signature data of the current block (namely the SR signature list)

```typescript

public void putBlockSignData(long blockNum, PbftSignCapsule item): Set

```

Get the signature data of the current block (namely the SR signature list)

```typescript

public PbftSignCapsule getBlockSignData(long blockNum)

```

Each vote is recorded as a message, so we define a message structure, PbftMessage, to cover all vote messages; please see full details under data structure.

```typescript

public class PbftMessage

```

The main aim of this data structure is to save signed commit messages and collect information on SRs who are signing current data; please see full details under data structure.

```typescript

public class DataSign

```

PbftBaseMessage encapsulates PbftMessage and supports features such as signing validation messages and creating prepare and commit messages

```typescript

public class PbftBaseMessage

```

**Comment by Dev-Tools-VM** [comment] 2021-04-02 08:47
`Once verifiers receive more than 2/3+1 replies commit messages from verifiers stating that block E is valid, which proves that block E on (b) is valid, which draws a conclusion that B,C,D,E are all valid and can be marked as solid status since each block hash was calculated from previous block hash`

As you mentioned above, Once E is confirmed, then BCD will be confirmed too. I got one question, it may also be related to #248 , here, let us assume A is confirmed, and BCD are all not confirmed.  then how does the SPV work? does this mean before E is confirmed all transactions inside BCD cannot be verified by SPV?   hope you can understand what I mean, thanks.

**Comment by spidemen** [comment] 2021-04-02 09:04
SPV only query confirmed blocks.

**Comment by Dev-Tools-VM** [comment] 2021-04-02 09:30
Another question, regarding the fork, regarding the rule 2, What is the trigger condition of rule 2, and how many unconfirmed blocks will be in the worst case?
```
Fork
Rule 1: always choose the fork chain which first receives 2/3 +1 Verifiers replicas commit messages as the main chain. Rule 2: if no block receives 2/3 +1 commit messages, then choose a longer chain as the main chain. Follow priority : rule1 >rule2.
```

**Comment by spidemen** [comment] 2021-04-02 09:50
B  ---- C
A   /
     \ 
       B1 ---- C1  ---- D1 ----- E1 ----- F1......... .
In worst case, it can be network down or internet is down, this will stop blockchain or it can be some region's network is down, which causes some of SRs down, which may leads to the number of unconfirmed block increase. In this case, at most one epoch time, which is 6 hours since next epoch will reselect SRs based on the number of votes each SR receives,  can be counted as worst cases, which is equivalent to (6*60/3) - 1 = 119 total blocks.

**Comment by MikumoGuynemer** [comment] 2021-04-02 10:43
Will the time period of synchronization be shortened together with the block confirmation time?
Can hybrid consensus bring other improvements to TRON(like, lowering the machine configuration requirements)?

**Comment by stablecoin2021** [comment] 2021-04-06 14:52
Will the time period of synchronization be shortened together with the block confirmation time?   no
Can hybrid consensus bring other improvements to TRON(like, lowering the machine configuration requirements)?  yes.  decrease transaction confirm time.

**Comment by spidemen** [comment] 2021-04-06 15:11
Will the time period of synchronization be shortened together with the block confirmation time? no
Can hybrid consensus bring other improvements to TRON(like, lowering the machine configuration requirements)? yes. decrease transaction confirm time.

Since every 3 second a block is produced, so the synchronization should be the same. hybrid consensus can also do help on cross-chain.

**Closed** 2023-06-13 09:36 UTC
